#!/bin/bash

USER='git config user.name'
EMAIL='git config user.email'

echo "Poject Name: "
read PROJECT

rm -rf .git
git init
curl -u "$(eval $EMAIL)" https://api.github.com/user/repos -d "{\"name\": \"$PROJECT\"}"
git remote add origin "git@github.com:$(eval ${USER})/${PROJECT}.git"


git add .
git commit -m "First commit"
git push -u origin master